import type { Cadena, Pelicula, Funcion, Descuento, Actualizacion } from "./types";

// ─── Static data (chains + discounts — maintained manually) ─────────────────
export const CADENAS: Cadena[] = [
  {
    id: "cinemark",
    nombre: "Cinemark",
    logo: "/logos/cinemark.svg",
    color: "#E31837",
    url_base: "https://www.cinemark.cl",
    url_compra: "https://www.cinemark.cl/comprar",
  },
  {
    id: "cinepolis",
    nombre: "Cinépolis",
    logo: "/logos/cinepolis.svg",
    color: "#FF6B00",
    url_base: "https://www.cinepolis.cl",
    url_compra: "https://www.cinepolis.cl/comprar",
  },
  {
    id: "cineplanet",
    nombre: "Cineplanet",
    logo: "/logos/cineplanet.svg",
    color: "#003087",
    url_base: "https://www.cineplanet.cl",
    url_compra: "https://www.cineplanet.cl/comprar",
  },
  {
    id: "muvix",
    nombre: "Muvix",
    logo: "/logos/muvix.svg",
    color: "#6B21A8",
    url_base: "https://www.muvix.cl",
    url_compra: "https://www.muvix.cl/comprar",
  },
];

export const DESCUENTOS: Descuento[] = [
  // Cinemark
  {
    id: "d1",
    cadena_id: "cinemark",
    banco_operador: "cmr_falabella",
    tipo: "porcentaje",
    valor: 30,
    condicion: "Hasta 2 entradas por función",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d2",
    cadena_id: "cinemark",
    banco_operador: "bancoestado",
    tipo: "porcentaje",
    valor: 25,
    condicion: "Miércoles y jueves",
    dias_valido: ["miércoles", "jueves"],
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d3",
    cadena_id: "cinemark",
    banco_operador: "entel",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Lunes a jueves",
    dias_valido: ["lunes", "martes", "miércoles", "jueves"],
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d13",
    cadena_id: "cinemark",
    banco_operador: "bci",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d14",
    cadena_id: "cinemark",
    banco_operador: "los_andes",
    tipo: "porcentaje",
    valor: 15,
    condicion: "Miércoles",
    dias_valido: ["miércoles"],
    vigente_hasta: "2025-06-30",
  },
  // Cinépolis
  {
    id: "d4",
    cadena_id: "cinepolis",
    banco_operador: "scotiabank_cencosud",
    tipo: "porcentaje",
    valor: 30,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d5",
    cadena_id: "cinepolis",
    banco_operador: "cmr_falabella",
    tipo: "porcentaje",
    valor: 25,
    condicion: "Lunes a jueves",
    dias_valido: ["lunes", "martes", "miércoles", "jueves"],
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d6",
    cadena_id: "cinepolis",
    banco_operador: "movistar",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d15",
    cadena_id: "cinepolis",
    banco_operador: "itau",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d16",
    cadena_id: "cinepolis",
    banco_operador: "los_heroes",
    tipo: "porcentaje",
    valor: 15,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  // Cineplanet
  {
    id: "d7",
    cadena_id: "cineplanet",
    banco_operador: "bancoestado",
    tipo: "porcentaje",
    valor: 30,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d8",
    cadena_id: "cineplanet",
    banco_operador: "entel",
    tipo: "porcentaje",
    valor: 25,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d9",
    cadena_id: "cineplanet",
    banco_operador: "cmr_falabella",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Lunes a jueves",
    dias_valido: ["lunes", "martes", "miércoles", "jueves"],
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d17",
    cadena_id: "cineplanet",
    banco_operador: "santander",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d18",
    cadena_id: "cineplanet",
    banco_operador: "la_araucana",
    tipo: "porcentaje",
    valor: 15,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  // Muvix
  {
    id: "d10",
    cadena_id: "muvix",
    banco_operador: "cmr_falabella",
    tipo: "porcentaje",
    valor: 30,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d11",
    cadena_id: "muvix",
    banco_operador: "scotiabank_cencosud",
    tipo: "porcentaje",
    valor: 25,
    condicion: "Miércoles",
    dias_valido: ["miércoles"],
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d12",
    cadena_id: "muvix",
    banco_operador: "movistar",
    tipo: "porcentaje",
    valor: 20,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
  {
    id: "d19",
    cadena_id: "muvix",
    banco_operador: "wom",
    tipo: "porcentaje",
    valor: 15,
    condicion: "Todos los días",
    vigente_hasta: "2025-06-30",
  },
];

// ─── Movie/showtime data (static JSON — update data/*.json manually) ──────────
import _peliculas from "../data/peliculas.json";
import _funciones from "../data/funciones.json";
import _actualizaciones from "../data/actualizaciones.json";

export const PELICULAS: Pelicula[] = _peliculas as Pelicula[];
export const FUNCIONES: Funcion[] = _funciones as Funcion[];
export const ACTUALIZACIONES: Actualizacion[] = _actualizaciones as Actualizacion[];
